# Generated by Django 4.2.10 on 2024-04-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_master_pay", "0005_auto_20230927_1102"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="record_data",
            field=models.JSONField(verbose_name="RAW data"),
        ),
    ]
